Revert deletion of `require('babel-core/register');` in config/config.js, PR #80
Caused the error on `yarn migrate`:
```
ERROR: Error reading "config/database.js". Error: SyntaxError: Unexpected token import
```

Without `require('babel-core/register');` near the application entry-point, babel transpilation does not occur